### ISSUE TITLE
Add quarantine for a client not passing the authentication/authorization

### ISSUE THREAD

**Issue by bwsw** [insight-platform/MediaGateway#29]
The quarantine time must be configured with the configuration file parameter.

**Comment by ksenia-vazhdaeva** [comment]
@bwsw , is tracking of eviction because of maximum quarantine capacity required? And should quarantine be restricted by capacity at all?

**Comment by bwsw** [comment]
@ksenia-vazhdaeva yes, out-of-capacity monitoring is required to let users know that they configured the service suboptimally. The same LRU implementation required.
